# Generated by Django 5.2.3 on 2025-07-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_address_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('support_worker', 'Support Worker'), ('practitioner', 'Practitioner'), ('family', 'Family'), ('super_admin', 'Super Admin')], default='support_worker', max_length=32),
        ),
    ]
