# Generated by Django 5.2.3 on 2025-07-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at', 'username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
