# Generated by Django 5.2.3 on 2025-06-30 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(choices=[('home', 'Home'), ('school', 'School'), ('community', 'Community'), ('therapy', 'Therapy'), ('transport', 'Transport'), ('other', 'Other')], default='other', max_length=20)),
                ('specific_location', models.CharField(blank=True, help_text='Specific location details', max_length=200, null=True)),
                ('activity_before', models.TextField(blank=True, help_text='What was happening before the behavior', null=True)),
                ('behavior_type', models.CharField(choices=[('aggression', 'Aggression'), ('self_injury', 'Self-Injury'), ('property_damage', 'Property Damage'), ('elopement', 'Elopement'), ('non_compliance', 'Non-Compliance'), ('disruption', 'Disruption'), ('other', 'Other')], default='other', max_length=20)),
                ('behaviors', models.JSONField(default=list, help_text='List of specific behaviors observed')),
                ('warning_signs', models.JSONField(blank=True, default=list, help_text='Warning signs observed before behavior')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration of the behavior in minutes', null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('harm_to_self', models.BooleanField(default=False)),
                ('harm_to_others', models.BooleanField(default=False)),
                ('property_damage', models.BooleanField(default=False)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('intervention_used', models.TextField(help_text='What intervention was used')),
                ('intervention_effective', models.BooleanField(blank=True, help_text='Was the intervention effective?', null=True)),
                ('intervention_notes', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of photo URLs')),
                ('videos', models.JSONField(blank=True, default=list, help_text='List of video URLs')),
                ('notes', models.TextField(blank=True, null=True)),
                ('triggers_identified', models.JSONField(blank=True, default=list, help_text='Potential triggers identified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Behavior Log',
                'verbose_name_plural': 'Behavior Logs',
                'db_table': 'behavior_logs',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
