# Generated by Django 5.2.3 on 2025-06-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completion_threshold',
            field=models.IntegerField(default=80, help_text='Percentage threshold to mark goal as completed'),
        ),
        migrations.AddField(
            model_name='goal',
            name='required_activities_count',
            field=models.IntegerField(default=0, help_text='Number of activities required to complete this goal'),
        ),
    ]
