# Generated by Django 5.2.3 on 2025-06-30 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('goals', '0002_goal_completion_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='goal',
        ),
        migrations.AddField(
            model_name='activity',
            name='goal_contribution_weight',
            field=models.IntegerField(default=1, help_text="Weight of this activity's contribution to goal progress (1-10)"),
        ),
        migrations.AddField(
            model_name='activity',
            name='primary_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_activities', to='goals.goal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_goals',
            field=models.ManyToManyField(blank=True, related_name='related_activities', to='goals.goal'),
        ),
    ]
