# Generated by Django 5.2.3 on 2025-06-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('behaviors', '0001_initial'),
        ('media', '0002_mediafile_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='activity_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='activities.activitylog'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='behavior_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='behaviors.behaviorlog'),
        ),
    ]
