# Generated by Django 5.2.3 on 2025-07-05 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_remove_activity_goal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('recurrence_type', models.CharField(choices=[('none', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='General notes about this scheduled activity', null=True)),
                ('preparation_notes', models.TextField(blank=True, help_text='Notes about preparation needed', null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Notes after completion', null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('send_reminder', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.IntegerField(default=30, help_text='Minutes before scheduled time to send reminder')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0, help_text='Percentage of activity completed (0-100)')),
                ('difficulty_rating', models.IntegerField(blank=True, help_text='Difficulty rating from 1-5', null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, help_text='Satisfaction rating from 1-5', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='activities.activity')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('parent_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='scheduler.schedule')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'unique_together': {('activity', 'assigned_user', 'scheduled_date', 'scheduled_time')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('time_overlap', 'Time Overlap'), ('resource_conflict', 'Resource Conflict'), ('user_double_booking', 'User Double Booking')], max_length=50)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('schedule1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_first', to='scheduler.schedule')),
                ('schedule2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_second', to='scheduler.schedule')),
            ],
            options={
                'verbose_name': 'Schedule Conflict',
                'verbose_name_plural': 'Schedule Conflicts',
                'db_table': 'schedule_conflicts',
            },
        ),
        migrations.CreateModel(
            name='ScheduleReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='scheduler.schedule')),
            ],
            options={
                'verbose_name': 'Schedule Reminder',
                'verbose_name_plural': 'Schedule Reminders',
                'db_table': 'schedule_reminders',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_duration', models.IntegerField(help_text='Default duration in minutes')),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('default_location', models.CharField(blank=True, max_length=200)),
                ('default_preparation_notes', models.TextField(blank=True)),
                ('default_reminder_minutes', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule Template',
                'verbose_name_plural': 'Schedule Templates',
                'db_table': 'schedule_templates',
            },
        ),
    ]
